/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de_1_java;

import static de_1_java.De_1_Java.CreListCHD;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author HP
 */
public class MainFrame extends javax.swing.JFrame {
    // Tạo danh sách Cung hoàng đạo
    ArrayList<CungHD> ListCHD = CreListCHD();

    /**
     * Creates new form jFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        addComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        frameC1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        resultTimeBefore = new javax.swing.JLabel();
        resultNameBefore = new javax.swing.JLabel();
        resultImgBefore = new javax.swing.JLabel();
        inputDay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputMonth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        resultName = new javax.swing.JLabel();
        resultTime = new javax.swing.JLabel();
        resultImg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        resultNameAfter = new javax.swing.JLabel();
        resultTimeAfter = new javax.swing.JLabel();
        resultImgAfter = new javax.swing.JLabel();
        frameC3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        resultName3 = new javax.swing.JLabel();
        resultTime3 = new javax.swing.JLabel();
        resultImg3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        resultTimeBefore3 = new javax.swing.JLabel();
        resultNameBefore3 = new javax.swing.JLabel();
        resultImgBefore3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        resultNameAfter3 = new javax.swing.JLabel();
        resultTimeAfter3 = new javax.swing.JLabel();
        resultImgAfter3 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ứng dụng xác định Cung hoàng đạo");
        setLocation(new java.awt.Point(0, 0));
        setName("mainFrame"); // NOI18N
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setName("frameC1"); // NOI18N
        background.setLayout(new java.awt.CardLayout());

        frameC1.setBackground(new java.awt.Color(249, 249, 249));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(59, 59, 59));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mời nhập...");

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("Nơi hiện thị kết quả");

        resultTimeBefore.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultTimeBefore.setForeground(new java.awt.Color(59, 59, 59));
        resultTimeBefore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultTimeBefore.setText(" ");

        resultNameBefore.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultNameBefore.setForeground(new java.awt.Color(59, 59, 59));
        resultNameBefore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultNameBefore.setText(" ");

        resultImgBefore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(resultNameBefore, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(resultTimeBefore, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(resultImgBefore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultImgBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultNameBefore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultTimeBefore)
                .addContainerGap())
        );

        inputDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputDay.setForeground(new java.awt.Color(59, 59, 59));
        inputDay.setToolTipText("Nơi nhập Ngày");
        inputDay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputDay.setName("inputDay"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(59, 59, 59));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ngày");

        inputMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputMonth.setForeground(new java.awt.Color(59, 59, 59));
        inputMonth.setToolTipText("Nơi nhập Tháng");
        inputMonth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputMonth.setName("inputMonth"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(59, 59, 59));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tháng");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(59, 59, 59));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Kết quả Cung hoàng đạo");

        btnSearch.setForeground(new java.awt.Color(59, 59, 59));
        btnSearch.setText("Tìm");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setName("btnSearch"); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("Nơi hiện thị kết quả");

        resultName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultName.setForeground(new java.awt.Color(59, 59, 59));
        resultName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultName.setText(" ");

        resultTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultTime.setForeground(new java.awt.Color(59, 59, 59));
        resultTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultTime.setText(" ");

        resultImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(resultImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultTime, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(resultImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultTime)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(243, 243, 243));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setToolTipText("Nơi hiện thị kết quả");
        jPanel3.setPreferredSize(new java.awt.Dimension(166, 177));

        resultNameAfter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultNameAfter.setForeground(new java.awt.Color(59, 59, 59));
        resultNameAfter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultNameAfter.setText(" ");

        resultTimeAfter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultTimeAfter.setForeground(new java.awt.Color(59, 59, 59));
        resultTimeAfter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultTimeAfter.setText(" ");

        resultImgAfter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(resultImgAfter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultNameAfter, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(resultTimeAfter, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultImgAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultNameAfter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultTimeAfter)
                .addContainerGap())
        );

        javax.swing.GroupLayout frameC1Layout = new javax.swing.GroupLayout(frameC1);
        frameC1.setLayout(frameC1Layout);
        frameC1Layout.setHorizontalGroup(
            frameC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameC1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameC1Layout.createSequentialGroup()
                        .addGroup(frameC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(frameC1Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameC1Layout.createSequentialGroup()
                        .addGap(0, 122, Short.MAX_VALUE)
                        .addGroup(frameC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameC1Layout.createSequentialGroup()
                                .addGroup(frameC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(frameC1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(inputDay, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(77, 77, 77)
                                .addGroup(frameC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(frameC1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(inputMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(125, 125, 125))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameC1Layout.createSequentialGroup()
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(207, 207, 207))))))
        );
        frameC1Layout.setVerticalGroup(
            frameC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameC1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(frameC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        background.add(frameC1, "card2");

        frameC3.setBackground(new java.awt.Color(249, 249, 249));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(59, 59, 59));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Mời chọn...");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(59, 59, 59));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cung hoàng đạo");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(59, 59, 59));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Kết quả Ngày\\Tháng");

        jPanel6.setBackground(new java.awt.Color(243, 243, 243));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setToolTipText("Nơi hiện thị kết quả");

        resultName3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultName3.setForeground(new java.awt.Color(59, 59, 59));
        resultName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultName3.setText(" ");

        resultTime3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultTime3.setForeground(new java.awt.Color(59, 59, 59));
        resultTime3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultTime3.setText(" ");

        resultImg3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(resultTime3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultName3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(resultImg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultImg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultTime3)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(243, 243, 243));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setToolTipText("Nơi hiện thị kết quả");

        resultTimeBefore3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultTimeBefore3.setForeground(new java.awt.Color(59, 59, 59));
        resultTimeBefore3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultTimeBefore3.setText(" ");

        resultNameBefore3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultNameBefore3.setForeground(new java.awt.Color(59, 59, 59));
        resultNameBefore3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultNameBefore3.setText(" ");

        resultImgBefore3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(resultImgBefore3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultNameBefore3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(resultTimeBefore3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultImgBefore3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultNameBefore3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultTimeBefore3)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(243, 243, 243));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setToolTipText("Nơi hiện thị kết quả");
        jPanel8.setPreferredSize(new java.awt.Dimension(166, 177));

        resultNameAfter3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultNameAfter3.setForeground(new java.awt.Color(59, 59, 59));
        resultNameAfter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultNameAfter3.setText(" ");

        resultTimeAfter3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultTimeAfter3.setForeground(new java.awt.Color(59, 59, 59));
        resultTimeAfter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultTimeAfter3.setText(" ");

        resultImgAfter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(resultImgAfter3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultNameAfter3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(resultTimeAfter3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultImgAfter3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultNameAfter3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultTimeAfter3)
                .addContainerGap())
        );

        comboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout frameC3Layout = new javax.swing.GroupLayout(frameC3);
        frameC3.setLayout(frameC3Layout);
        frameC3Layout.setHorizontalGroup(
            frameC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameC3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(frameC3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameC3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frameC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(155, 155, 155))
        );
        frameC3Layout.setVerticalGroup(
            frameC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameC3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        background.add(frameC3, "card3");

        jMenuBar1.setBackground(new java.awt.Color(225, 225, 225));
        jMenuBar1.setForeground(new java.awt.Color(59, 59, 59));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu4.setText("|");
        jMenu4.setEnabled(false);
        jMenu4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuBar1.add(jMenu4);

        jMenu1.setForeground(new java.awt.Color(59, 59, 59));
        jMenu1.setText("Ngày/Tháng -> Cung Hoàng đạo");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("|");
        jMenu3.setEnabled(false);
        jMenu3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuBar1.add(jMenu3);

        jMenu2.setForeground(new java.awt.Color(59, 59, 59));
        jMenu2.setText("Cung Hoàng đạo -> Ngày/Tháng");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu5.setText("|");
        jMenu5.setEnabled(false);
        jMenu5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Hiện frame chạy ý 3
    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        frameC1.setVisible(false);
        frameC3.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    // Hiện frame chạy ý 1
    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        frameC1.setVisible(true);
        frameC3.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    // Tìm ra khoảng phù hợp với thời gian nhập trong danh sách Cung
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        boolean run = false;
        try {
            run = check();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Vui lòng không để trống ô nhập và chỉ nhập số","Cảnh báo",JOptionPane.WARNING_MESSAGE);
        }
        
        if(run) {
            int day = Integer.parseInt(inputDay.getText());
            int month = Integer.parseInt(inputMonth.getText());
            ArrayList<CungHD> result = new ArrayList<CungHD>();
            ArrayList<CungHD> resultBefore = new ArrayList<CungHD>();
            ArrayList<CungHD> resultAfter = new ArrayList<CungHD>();

            // Lấy ra 2 Cung trùng với tháng nhập
            for (CungHD i : ListCHD) {
                if (month == i.getMonthStart() || month == i.getMonthEnd()) {
                    result.add(i);
                }
            }

            // Sắp xếp lại thứ tự 2 Cung vừa lấy theo dạng:
            // Cung1 (tháng_bắt_đầu - tháng_nhập)
            // Cung2 (tháng_nhập - tháng_kết_thúc)
            result.sort((x, y) -> x.getMonthStart() == y.getMonthEnd() ? 1 : -1);

            // Trả về Cung có khoảng phù hợp với thời gian nhập
            // Nếu Cung1 có tháng_bắt_đầu != tháng_nhập và ngày_kết_thúc <= ngày_nhập
            // thì lấy Cung1 hoặc không thì lấy Cung2
            if (day <= result.get(0).getDayEnd()) {
                showResult(result, 0);
            } else {
                showResult(result, 1);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    
    // In ra tên và thời gian của Cung trong khoảng thời gian nhập
    // 2 Cung trái và phải bị thừa do đọc nhầm đề :P
    private void showResult(ArrayList<CungHD> list, int index) {
        int tempIndex = list.get(index).getId();
//        System.out.println(tempIndex);
        
        // Thừa đến hết if else
        ArrayList<CungHD> temp = new ArrayList<CungHD>();
        if(list.get(index).getId() - 1 == -1) {
            temp.add(ListCHD.get(11));
        } else {
            temp.add(ListCHD.get(tempIndex - 1));
        }
        if(list.get(index).getId() + 1 == 12) {
            temp.add(ListCHD.get(0));
        } else {
            temp.add(ListCHD.get(tempIndex + 1));
        }

        // Thừa 2 dòng dưới
        resultImgBefore.setIcon(genImg(temp, temp.get(0).getId()));
        resultNameBefore.setText(genName(temp, 0));
        resultTimeBefore.setText(genDate(temp, 0));

        resultImg.setIcon(genImg(list, ListCHD.get(tempIndex).getId()));
        resultName.setText(genName(list, index));
        resultTime.setText(genDate(list, index));

        // Thừa 2 dòng dưới
        resultImgAfter.setIcon(genImg(temp, temp.get(1).getId()));
        resultNameAfter.setText(genName(temp, 1));
        resultTimeAfter.setText(genDate(temp, 1));
    }
    
    // Load danh sách Cung lên ComboBox
    private void addComboBox() {
        for (CungHD i : ListCHD) {
            comboBox.addItem(i.getName());
        }
        // comboBox.setSelectedIndex(-1);
    }

    // Chọn Cung nào thì hiện cung đấy ở giữa
    // Bên trái là Cung trước và phải là cung sau
    private void comboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxItemStateChanged
        int index = comboBox.getSelectedIndex();
        int indexBefore = comboBox.getSelectedIndex() - 1;
        int indexAfter = comboBox.getSelectedIndex() + 1;
        
        // Chọn lại index cho Cung đầu quay về Cung cuối trong danh sách
        if(indexBefore == -1) {
            indexBefore = 11;
        }
        
        // Chọn lại index cho Cung cuối quay về Cung đầu trong danh sách
        if(indexAfter == 12) {
            indexAfter = 0;
        }
        
        // Đẩy dữ liệu ra
        resultImgBefore3.setIcon(genImg(ListCHD, indexBefore));
        resultNameBefore3.setText(genName(ListCHD, indexBefore));
        resultTimeBefore3.setText(genDate(ListCHD, indexBefore));
        
        resultImg3.setIcon(genImg(ListCHD, index));
        resultName3.setText(genName(ListCHD, index));
        resultTime3.setText(genDate(ListCHD, index));
        
        resultImgAfter3.setIcon(genImg(ListCHD, indexAfter));
        resultNameAfter3.setText(genName(ListCHD, indexAfter));
        resultTimeAfter3.setText(genDate(ListCHD, indexAfter));
    }//GEN-LAST:event_comboBoxItemStateChanged

    // Lấy ảnh Cung
    private ImageIcon genImg(ArrayList<CungHD> list, int index) {
        // Giải thích cái này hơi phức tạp...
        // Tóm lại mục đích chính là để sửa lại kích thước ảnh hiện thị
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("src/de_1_java/img/" + index + ".png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(100, 100,Image.SCALE_SMOOTH);
        
        ImageIcon icon = new ImageIcon(dimg);
        return icon;
    }
    // Lấy tên Cung
    private String genName(ArrayList<CungHD> list, int index) {
        return list.get(index).getName();
    }
    
    // Lấy thời gian Cung
    private String genDate(ArrayList<CungHD> list, int index) {
        return list.get(index).getDayStart() + "/" + list.get(index).getMonthStart() + " - " + list.get(index).getDayEnd() + "/" + list.get(index).getMonthEnd();
    }
    
    // Check các điều kiện
    private boolean check() {
        int day = Integer.parseInt(inputDay.getText());
        int month = Integer.parseInt(inputMonth.getText());
        if(month < 1 || month > 12) {
            JOptionPane.showMessageDialog(null,"1 năm chỉ có 12 tháng và bắt đầu từ tháng 1","Cảnh báo",JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            switch(month) {
                case 1:
                case 3:
                case 5:
                case 7:
                case 8:
                case 10:
                case 12:
                    if(day < 1 || day > 31) {
                        JOptionPane.showMessageDialog(null,"Tháng " + month + " chỉ có 31 ngày và bắt đầu từ ngày 1","Cảnh báo",JOptionPane.WARNING_MESSAGE);
                        return false;
                    }
                    break;
                case 4:
                case 6:
                case 9:
                case 11:
                    if(day < 1 || day > 30) {
                        JOptionPane.showMessageDialog(null,"Tháng " + month + " chỉ có 30 ngày và bắt đầu từ ngày 1","Cảnh báo",JOptionPane.WARNING_MESSAGE);
                        return false;
                    }
                    break;
                default:
                    if(day < 1 || day > 29) {
                        JOptionPane.showMessageDialog(null,"Tháng " + month + " chỉ có 28 ngày (năm nhuận thì 29 ngày) và bắt đầu từ ngày 1","Cảnh báo",JOptionPane.WARNING_MESSAGE);
                        return false;
                    }
                    break;
            }
            return true;
        }
            
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JPanel frameC1;
    private javax.swing.JPanel frameC3;
    private javax.swing.JTextField inputDay;
    private javax.swing.JTextField inputMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel resultImg;
    private javax.swing.JLabel resultImg3;
    private javax.swing.JLabel resultImgAfter;
    private javax.swing.JLabel resultImgAfter3;
    private javax.swing.JLabel resultImgBefore;
    private javax.swing.JLabel resultImgBefore3;
    private javax.swing.JLabel resultName;
    private javax.swing.JLabel resultName3;
    private javax.swing.JLabel resultNameAfter;
    private javax.swing.JLabel resultNameAfter3;
    private javax.swing.JLabel resultNameBefore;
    private javax.swing.JLabel resultNameBefore3;
    private javax.swing.JLabel resultTime;
    private javax.swing.JLabel resultTime3;
    private javax.swing.JLabel resultTimeAfter;
    private javax.swing.JLabel resultTimeAfter3;
    private javax.swing.JLabel resultTimeBefore;
    private javax.swing.JLabel resultTimeBefore3;
    // End of variables declaration//GEN-END:variables
}
